set(CPACK_PACKAGE_CONTACT             "Aqua Tracker")
set(CPACK_PACKAGE_NAME                "atdbwritertimerd")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Aqua Tracker Database Writer Client Caller Demon")
set(CPACK_PACKAGE_VENDOR              "Aqua Tracker")
set(CPACK_PACKAGE_FILE_NAME           "atdbwritertimerd_1.0.0")
set(CPACK_DEBIAN_PACKAGE_SECTION      "non-free")
set(CPACK_DEBIAN_PACKAGE_DEPENDS      "qt5-default")
find_program(DPKG NAMES dpkg)
set(CPACK_GENERATOR "DEB")
include(CPack)